org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod Properties
# check these on https://fabricmc.net/develop
mod.id=elytratrims
mod.name=Elytra Trims
mod.group=dev.kikugie
mod.version=4.1.0

deps.fabric-loader=0.16.14
deps.fabric-kotlin=1.13.3+kotlin.2.1.21

publish.modrinth=XpzGz7KD
publish.curseforge=876199
