org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
#org.gradle.configuration-cache=true

# Mod Properties
# check these on https://fabricmc.net/develop
mod.id=elytratrims
mod.name=Elytra Trims
mod.group=dev.kikugie
mod.version=4.0.0-alpha.5

deps.fabric-loader=0.16.10
deps.fabric-kotlin=1.13.1+kotlin.2.1.10
