# Done to increase the memory available to gradle.
#fabric.loom.multiProjectOptimisation=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

# Mod Properties
mod.version=3.5.8
mod.group=dev.kikugie
mod.id=elytratrims
mod.name=Elytra Trims

# Global Dependencies
deps.mixin_squared=0.1.2-beta.4
deps.mixin_extras=0.4.1
deps.cond_mixin=0.6.3
deps.fabric_loader=0.16.9
deps.flk=1.13.0
deps.kff=4.11.0

# Versioned Dependencies
deps.minecraft=[VERSIONED]
deps.yarn_build=[VERSIONED]
deps.fapi=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fml=[VERSIONED]
deps.compat=[VERSIONED]
mod.mc_dep=[VERSIONED]
mod.mc_title=[VERSIONED]
mod.mc_targets=[VERSIONED]

publish.modrinth=XpzGz7KD
publish.curseforge=876199
